version: "3.9"
services:
  inst1:
    build: .
    container_name: whatsapp-ws-inst1
    platform: linux/amd64
    networks:
      whatsapp-net:
        ipv4_address: 172.25.0.11
    ports:
      - "3001:3000"
    environment:
      TZ: America/Sao_Paulo
      NODE_ENV: production
      PGHOST: db        # 👉 nome do serviço do banco
      PGUSER: whatsapp
      PGPASSWORD: 1q2w3e4r
      PGDATABASE: whatsapp
      PGPORT: 5432      
    volumes:
      - ./sessions/inst1:/app/sessions
    restart: unless-stopped

  # inst2:
  #   build: .
  #   image: whatsapp-ws:latest
  #   platform: linux/amd64
  #   container_name: whatsapp-ws-inst2
  #   networks:
  #     whatsapp-net:
  #       ipv4_address: 172.25.0.12
  #   ports:
  #     - "3002:3000"
  #   environment:
  #     TZ: America/Sao_Paulo
  #     NODE_ENV: production
  #     PGHOST: db
  #     PGUSER: whatsapp
  #     PGPASSWORD: 1q2w3e4r
  #     PGDATABASE: whatsapp
  #     PGPORT: 5432
  #   volumes:
  #     - ./sessions/inst2:/app/sessions
  #   restart: unless-stopped

networks:
  whatsapp-net:
    external: true